// config/features.js
export const FEATURES = {
  ENABLE_PARTICLES: true,
  ENABLE_PARALLAX: true,
  ENABLE_MOTION: true,
  NOISE_OPACITY: 0.08,
  PARTICLE_COUNT_MULTIPLIER: 1.0,
  PARALLAX_MAX_OFFSET: 30,
  CHART_MAX_SERIES: 5,
  TABLE_DENSE_DEFAULT: false,
  FOCUS_RING_SIZE: 3
};